-- 코드를 입력하세요
With a AS (
    SELECT ANIMAL_ID FROM ANIMAL_INS
    EXCEPT
    SELECT ANIMAL_ID FROM ANIMAL_OUTS
)
SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID IN (SELECT ANIMAL_ID FROM a)
ORDER BY 2
LIMIT 3