-- 코드를 입력하세요
SELECT b.CATEGORY, SUM(bs.SALES) TOTAL_SALES
FROM BOOK_SALES bs JOIN BOOK b ON bs.BOOK_ID = b.BOOK_ID 
-- WHERE LEFT(bs.SALES_DATE, 7) = '2022-01'
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY 1
ORDER BY 1